### ISSUE TITLE
Failed initializing schema ingress-networking-v1.json 404

### ISSUE THREAD

**Issue by dombisza** [instrumenta/kubeval#301]
hello there,
i was trying to validate ingresses, but I cannot do some because the schema URL gives me 404.
```
linux@sdombi-vpc-bastion:~$ cat ingress2.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80
linux@sdombi-vpc-bastion:~$ kubeval ingress2.yaml
ERR  - ingress2.yaml: Failed initializing schema https://kubernetesjsonschema.dev/master-standalone/ingress-networking-v1.json: Could not read schema from HTTP, response status is 404 Not Found
linux@sdombi-vpc-bastion:~$ kubeval --version
Version: 0.16.1
Commit: f5dba6b486fa18b9179b91e15eb6f2b0f7a5a69e
Date: 2021-03-30T15:17:06Z
```
Am i doing something wrong here?
Thanks for the help in advance.

**Comment by izorster** [comment]
Not isolated to ingress:
Failed initializing schema https://kubernetesjsonschema.dev/master-standalone/certificate-cert-manager-v1.json: Could not read schema from HTTP, response status is 404 Not Found

**Comment by andrei-dascalu** [comment]
Likewise.
I can use versions that appear on main page https://kubernetesjsonschema.dev

But for example I can't specify various 1.20.x patches (or anything 1.20 for that matter) or 1.19 or the like

**Comment by tmikulin** [comment]
Will there be a patch soon? Or is there a workaround?

**Comment by yannh** [comment]
For newer versions of Kubernetes, try using  kubeval with my fork of the json schema repos: https://github.com/yannh/kubernetes-json-schema
See README for how to use those with kubeval. It contains schemas for all versions of Kubernetes post 1.15.

This should solve the errors related to Kubernetes versions. 

Things such as certificate-cert-manager-v1.json I believe are CRDs from https://github.com/jetstack/cert-manager , and a different problem?

**Comment by knkarthik** [comment]
> For newer versions of Kubernetes, try using kubeval with my fork of the json schema repos: https://github.com/yannh/kubernetes-json-schema
> See README for how to use those with kubeval. It contains schemas for all versions of Kubernetes post 1.15.
> 
> This should solve the errors related to Kubernetes versions.
> 
> Things such as certificate-cert-manager-v1.json I believe are CRDs from https://github.com/jetstack/cert-manager , and a different problem?

@yannh Nice work! Wondering if you tried getting your changes merged to this repo. It would be nice to have only one place to refer. That being said I don't know what's the process of merging PRs here, as I can see lots of them still unmerged.

**Comment by jeremybusk** [comment]
As noted above to use newer schemas use command  like below

kubeval --schema-location https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master -d mydirectory

**Comment by Gaurav2586** [comment]
@yannh I run. the below command but still getting error , can you please help.
command :- kubeval -v 1.19.14 -s  https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master ingress.yaml

error: - Failed to decode YAML from ingress.yaml: error converting YAML to JSON: yaml: did not find expected node content

my kubectl version:-
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.14-gke.1900", GitCommit:"abc4e63ae76afef74b341d2dba1892471781604f", GitTreeState:"clean", BuildDate:"2021-09-07T09:21:04Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.19) exceeds the supported minor version skew of +/-1

**Comment by aguglie** [comment]
Thank you @jeremybusk  🚀 

For a long lasting fix, I applied an alias:

```bash
alias kubeval="kubeval --schema-location https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master "
```

**Comment by mmisztal1980** [comment]
I've tried applying the fix:
```bash
for file in $(find ./output -type f -iname '*.y*ml'); do
  kubeval --schema-location https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master $file --strict
done
```

I'm getting:

```
1 error occurred:
	* Failed initalizing schema https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/ingress-networking-v1.json: Get https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/ingress-networking-v1.json: EOF


1 error occurred:
	* Failed initalizing schema https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/service-v1.json: Get https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/service-v1.json: EOF


1 error occurred:
	* Failed initalizing schema https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment-apps-v1.json: Get https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment-apps-v1.json: EOF


1 error occurred:
	* Failed initalizing schema https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/cronjob-batch-v1.json: Get https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/cronjob-batch-v1.json: EOF
```

Am I doing anything wrong?

**Comment by alfchee** [comment]
> For newer versions of Kubernetes, try using kubeval with my fork of the json schema repos: https://github.com/yannh/kubernetes-json-schema See README for how to use those with kubeval. It contains schemas for all versions of Kubernetes post 1.15.
> 
> This should solve the errors related to Kubernetes versions.
> 
> Things such as certificate-cert-manager-v1.json I believe are CRDs from https://github.com/jetstack/cert-manager , and a different problem?

thanks! this is very helpful

**Comment by jheidbrink** [comment]
For anyone stumbling upon this: Since october 2022, the readme states that this project is unmaintained and recommends `kubeconform` instead.
